### ISSUE TITLE
Missing package informations and details

### ISSUE THREAD

**Issue by ToX82** [jsdelivr/www.jsdelivr.com#129]
I am the owner of the package [cookieBAR](https://www.jsdelivr.com/package/gh/ToX82/cookie-bar)

I'd like to show some additional information about the package in its page, like tags, home page, description etc. I have published a package.json file containing all of those informations, but still those informations are not shown.

What is the right way to insert those data?

**Comment by MartinKolarik** [comment]
While jsDelivr supports serving files from both npm and GitHub, our website search currently only supports npm, and the additional package info you can see on other project pages are part of the search functionality. If you want a nicer project page, you'll need to publish your package to npm and use `/npm/` links instead of `/gh/`

**Comment by MartinKolarik** [comment]
@ToX82 let me know if you have any more questions regarding this or need any other help.

**Comment by ToX82** [comment]
That answered to my questions, thanks!
