### ISSUE TITLE
Smart social media images

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#392]
Let's do something similar https://github.blog/2021-06-22-framework-building-open-graph-images/

e.g. https://github.com/vercel/og-image

**Comment by jimaek** [comment]
Info to show:

- name + avatar
- description
- jsdelivr branding
- latest version
- hits per month
- GB per month
- Maybe a small simple chart with stats?

**Comment by jimaek** [comment]
Design. For SVG check Figma or ask designer
![og_image](https://user-images.githubusercontent.com/1834071/146989491-4e230d08-66c0-4f68-8537-bbf0ca972955.png)

**Comment by zarianec** [comment]
This is an svg->png example. It looks well and renders in ~30ms (which is fast). The anti-aliasing for a bootstrap logo is not perfect though (since the original logo is a raster image).

The actual preview width for Twitter is ~500px in tweets list, and ~560px on the tweet page (like [here](https://twitter.com/LEGOEngineering/status/1471414177763938308)).

@jimaek should we make text and graphs bigger?

<img src="https://user-images.githubusercontent.com/3776001/147090495-85f9b3e6-ca4d-4b35-9977-228dfa63aed2.png" width="500px" />

**Comment by jimaek** [comment]
If it will look better sure
