### ISSUE TITLE
Search results seem to be incorrect.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jsdelivr/www.jsdelivr.com#48]
The query `http://lb.jimaek.svc.tutum.io/?query=fabri` doesn't seem to retrieve the correct results. The same search `fabri` doesn't retrieve any results in the current website. 

![](http://storage4.static.itmages.com/i/15/0803/h_1438581387_9199448_43f19c1cd6.png)

**Comment by MartinKolarik** [comment]
In addition to project name, it's also searching in author's name and project's description. I think this can be useful (happened to me a few times that I didn't know exact project name but remembered the author), and it doesn't mean less relevant results - project name is given higher priority than author and description. In this specific case, there's no "fabri" project, so you get this arguably less relevant results instead of nothing.

**Comment by abishekrsrikaanth** [comment]
i do understand the first result item which contains the author name "Fabrizio Balliano" because the search keyword contains it, but not sure what the rest of the results are for searching `fabri`.

Should it also get results where it matches:
- fab
- bri
- fa
etc....

**Comment by MartinKolarik** [comment]
We also have "typo tolerance" of one letter, which means "Fabi" and "Fari" also match "Fabri".
